internal_categories:

  - title: MIT Faculty
    key: mit_faculty

  - title: MIT Physics
    key: mit_physics

  - title: MIT Laboratory for Nuclear Science
    key: mit_lns

  - title: MIT Center for Theoretical Physics
    key: mit_ctp

  - title: MIT Social and Ethical Responsibilities of Computing
    key: mit_serc

  - title: MIT Statistics and Data Science Center
    key: mit_sdsc

  - title: MIT International Science and Technology Initiatives
    key: mit_misti

  - title: Before MIT
    key: before_mit
    
external_categories:

  - title: Advisory Boards
    key: advisory_boards

  - title: Workshop/Conference Organization
    key: workshops

  - title: Journal Editing
    key: journal_editing

mit_faculty:

  - name: MIT Faculty Committee on Curricula
    short_name: Committee on Curricula
    url:  https://registrar.mit.edu/faculty-curriculum-support/faculty-curriculum-committees/committee-curricula
    dates: Fall 2017-Spring 2020
    
mit_physics:

  - name: MIT Physics Ad Hoc Committee on Graduate Student Professional Development
    dates: Spring 2023
    
  - name: MIT Physics Graduate Admissions Committee
    dates: Spring 2021, Spring 2024
    
  - name: MIT Physics Communic.8 Faculty Liaison
    url:  https://piazza.com/mit/fall2020/communic8
    dates: Fall 2020-Fall 2023
    
  - name: MIT Physics Promotion Committee
    dates: "Fall 2019; Chair: Fall 2020, Fall 2021, Fall 2022"
    
  - name: MIT Physics Pappalardo Fellowships Executive Committee
    url: https://physics.mit.edu/research/pappalardo-fellowships-in-physics/
    dates: Fall 2016-Fall 2017
    
  - name: MIT Physics Colloquium Committee
    dates: "Spring 2010-Spring 2012; Chair: Fall 2012-Spring 2014"
      
  - name: MIT Physics Part II Qualifying Written Exam Committee
    dates: "Spring 2012-Spring 2013; Chair: Fall 2013-Spring 2014"
    
  - name: MIT Physics Part II Qualifying Written Exam Grading Committee
    dates: September 2010, January 2020


mit_lns:

  - name: MIT LNS Advisory Group
    dates: Fall 2017, Spring 2020-Present
    
  - name: MIT LNS Colloquium Committee
    dates: "Fall 2015-Spring 2017; Chair: Fall 2017-Spring 2018"

mit_ctp:

  - name: MIT CTP Part III Oral Qualifying Exam Committee
    dates: Spring 2015-Spring 2017, Fall 2022-Spring 2023
    
  - name: MIT CTP Faculty Mentor
    dates: April 2021-Present

  - name: MIT CTP Faculty Search Committee
    dates: "Fall 2017, Fall 2021, Fall 2023; Chair: Fall 2019"

  - name: MIT CTP Deputy Group Leader in High-Energy Physics
    dates: Spring 2020-Present

  - name: MIT CTP Visitor Coordinator
    dates: Fall 2016-Present

  - name: MIT CTP Nuclear/Particle Seminar Committee
    dates: Fall 2010-Fall 2016, Fall 2020-Spring 2021, Fall 2022-Present

  - name: MIT CTP Postdoc Selection Committee
    dates: Fall 2009-Present

mit_serc:

  - name: MIT SERC Seed Grant Selection Committee
    dates: Spring 2024

mit_sdsc:

  - name: MIT Physics, Statistics, and Data Science (PhysSDS) Committee
    url: https://web.mit.edu/physics/current/graduate/psds_phd.html
    dates: "Co-Chair: Fall 2020-Present"

mit_misti:

  - name: MISTI Global Seed Funds Evaluation Committee
    dates: Fall 2012, Fall 2013, Fall 2014

before_mit:

  - name: Berkeley CTP Particle Seminar Organizer
    dates: 2007-2009
    
  - name: Miller Symposium Committee
    dates: 2008-2009

journal_editing:

  - job: Editorial Board
    name: Journal of High Energy Physics
    url: https://jhep.sissa.it/
    dates: Fall 2019-Present
    
  - job: Editorial College
    name: SciPost Physics
    url: https://scipost.org/SciPostPhys
    dates: Fall 2019-Present
  
  - job: Co-Topic Editor
    issue: Efficient AI in Particle Physics and Astrophysics
    issue_url: https://www.frontiersin.org/research-topics/19095/efficient-ai-in-particle-physics-and-astrophysics
    org: Frontiers in Artificial Intelligence
    org_url: https://www.frontiersin.org/journals/artificial-intelligence
    dates: Spring 2022

peer_review:

  - name: Physical Review Letters
  - name: Journal of High Energy Physics
  - name: Physical Review D
  - name: SciPost Physics
  - name: Journal of Cosmology and Astroparticle Physics
  - name: Physics of the Dark Universe
  - name: Nuclear Physics B
  - name: Physics Letters B
  - name: European Physical Journal C
  - name: Journal of Physics G
  - name: Physics Reports
  - name: Annals of Physics
  - name: Particle Data Group


agency_review:

  - name: U.S. Department of Energy (DOE)
  - name: National Science Foundation (NSF)
  - name: European Research Council (ERC)
  - name: Heising-Simons Foundation
  - name: Research Corporation for Science Advancement (Cottrell)
  - name: The Royal Society
  - name: Swiss National Science Foundation
  - name: Natural Sciences & Engineering Research Council of Canada
  - name: Israel Science Foundation
  - name: Netherlands Organisation for Scientific Research
  - name: German Academic Exchange Service (DAAD)
  - name: French National Research Agency
  - name: Hungarian National Research, Development & Innovation Office


advisory_boards:

  - job: International Scientific Advisory Board
    name: AI for Science and Science for AI (AISSAI) Center
    url: https://www.cnrs.fr/en/artificial-intelligence-science-science-artificial-intelligence-aissai-center
    org: French CNRS
    dates: 2022-Present
    
  - job: International Advisory Committee
    name: Machine Learning Physics
    url: https://mlphys.scphys.kyoto-u.ac.jp/en/
    org: JSPS/MEXT Grant-in-Aid for Transformative Research Areas
    dates: 2022-2026

  - job: Science Advisory Board
    name: USQCD Collaboration
    url: https://www.usqcd.org/
    dates: Spring 2013-Fall 2016
  
  - job: Fellowship Selection Committee
    name: LHC Theory Initiative
    url: https://www.pas.rochester.edu/~orr/LHC-TI/Home.html
    dates: "Fall 2013-Fall 2014; Chair: Fall 2014"


institutions:
  - acp
  - aps
  - hepap
  
acp:
  name: Aspen Center for Physics (ACP)
  url:  https://www.aspenphys.org/
  roles:
  
    - job:   General Member
      dates: Summer 2020-Summer 2025
  
    - job:   Admissions Committee
      dates: Summer 2024

    - job:   Nominations Committee
      dates: "Summer 2021; Chair: Summer 2022; Ex officio: Summer 2023"
      
    - job:   Summer Program Committee
      dates: Summer 2020

    - job:   Conference Liaison
      issue: Theoretical Physics for Machine Learning
      dates: Winter 2023
    
    - job:   Workshop Organizer
      issue: Interplay of Fundamental Physics and Machine Learning
      dates: Summer 2022
      
    - job:   Workshop Organizer
      issue: "The LHC Awakens: A New Energy Frontier"
      dates: Summer 2016

    - job:   Workshop Organizer
      issue: "Year One of the LHC"
      dates: Summer 2011
      
    - job:   Conference Organizer
      issue: "New Data from the Energy Frontier"
      dates: Winter 2011


aps:
  name: American Physical Society (APS)
  url:  https://www.aps.org/
  roles:

    - job:   Fellow
      dates: 2022-Present

    - job:   Sakurai Dissertation Award Selection Committee
      dates: "Fall 2016; Vice Chair: Fall 2022; Chair: Fall 2023"

    - job:   Member
      dates: 2002-Present


hepap:
  name: High Energy Physics Advisory Panel (HEPAP)
  url:  https://science.osti.gov/hep/hepap
  roles:

    - job:   Particle Physics Project Prioritization Panel (P5)
      dates: December 2022-December 2023

    - job:   HEPAP Member
      dates: August 2021-March 2024
            
    - job:       HEPAP Presentation
      job_url:   https://science.osti.gov/hep/hepap/Meetings/202012
      issue:     The NSF AI Institute for Artificial Intelligence and Fundamental Interactions
      issue_url: https://github.com/jdthaler/jdthaler.github.io/raw/main/talks/jthaler_2020_12_IAIFI_HEPAP_Overview.pdf
      dates:     December 2020
      
    - job:       HEPAP Presentation
      job_url:   https://science.osti.gov/hep/hepap/Meetings/201905
      issue:     The High Energy Physics Landscape in 2019
      issue_url: https://github.com/jdthaler/jdthaler.github.io/raw/main/talks/jthaler_2019_05_HEPAP.pdf
      dates:     May 2019
  
workshops:

  - job: Organizer
    issue: "TASI 2024: The Frontiers of Particle Theory"
    issue_url:  https://www.colorado.edu/physics/events/summer-intensive-programs/theoretical-advanced-study-institute-elementary-particle-physics-current
    org:  CU Boulder
    dates:  June 2024

  - job:  Advisory Committee
    issue: "ML4Jets"
    issue_url: https://indico.cern.ch/event/1253794/
    org: DESY
    dates: November 2023

  - job:  Advisory Committee
    issue: "ML4Jets"
    issue_url: https://indico.cern.ch/event/1159913/
    org: Rutgers
    dates: November 2022

  - job: Topical Convener
    issue: Collider Phenomenology
    issue_url: https://snowmass21.org/theory/phenomenology
    org: Snowmass Theory Frontier
    org_url: https://snowmass21.org/theory/start
    dates: July 2021, July 2022
    
  - job:  Advisory Committee and Ombuds Team (with Ayana Arce)
    issue: "Boost 2022"
    issue_url: https://indico.cern.ch/event/1144064/
    org: Hamburg
    dates: August 2022

  - job:  Organizer
    issue: "Machine Learning at GGI"
    issue_url: https://agenda.infn.it/event/32043/
    org: Galileo Galilei Institute
    dates: August/September 2022
    
  - job:  Advisory Committee and Ombuds Team (with Ayana Arce)
    issue: "Boost 2021"
    issue_url: https://indico.cern.ch/event/1037559/
    org: Online
    dates: August 2021
    
  - job:  Advisory Committee
    issue: "ML4Jets"
    issue_url: https://indico.cern.ch/event/980214/
    org: Heidelberg
    dates: July 2021
    
  - job:  Organizer
    issue: "CMS Open Data for Theorists"
    issue_url: https://indico.cern.ch/e/CMSOpenDataForTheorists
    org: Fermilab/Virtual
    dates: September 2020
    
  - job:  Advisory Committee and Ombuds Team (with Ayana Arce)
    issue: "Boost 2020"
    issue_url: https://indico.cern.ch/e/boost2020
    org: Hamburg
    dates: July 2020
    
  - job:  Advisory Committee
    issue: "Machine Learning for Particle Physics"
    issue_url: https://indico.mitp.uni-mainz.de/event/199/
    org: Mainz
    dates: May 2020 â†’ June 2021
    
  - job:  Advisory Committee
    issue: "ML4Jets"
    issue_url: https://indico.cern.ch/event/809820/
    org: New York
    dates: January 2020
    
  - job: Local Organizing Committee
    issue: "Boost 2019"
    issue_url: https://indico.cern.ch/e/boost2019
    org: MIT
    dates: July 2019
    
  - job:  Advisory Committee
    issue: "Boost 2018"
    issue_url: https://indico.cern.ch/e/boost2018
    org: Paris
    dates: July 2018
    
  - job: Local Organizing Committee
    issue: "Rising Stars in Physics"
    issue_url: https://physicsrisingstars.mit.edu/
    org: MIT
    dates: April 2018
    
  - job:  Advisory Committee
    issue: "Boost 2017"
    org: Buffalo
    dates: July 2017
    
  - job: Jet Convener
    issue: "Physics at TeV Colliders"
    org: Les Houches
    dates: June 2017
    
  - job:  Advisory Committee
    issue: "BLV 2017"
    org: Cleveland
    dates: May 2017
    
  - job:  Scientific Organizing Committee
    issue: "Lattice for BSM Physics 2017"
    org: Boston
    dates: April 2017
    
  - job:  Advisory Committee
    issue: "Boost 2016"
    org: Zurich
    dates: July 2016
    
  - job:  Organizer
    issue: "Gearing up for LHC13"
    org: Galileo Galilei Institute
    dates: Fall 2015
    
  - job:  Advisory Committee
    issue: "Boost 2015"
    org: Chicago
    dates: August 2015
    
  - job: Jet Convener
    issue: "Physics at TeV Colliders"
    org: Les Houches
    dates: June 2015
    
  - job:  Advisory Committee
    issue: "Boost 2014"
    org: London
    dates: August 2014
    
  - job:  Organizer
    issue: "Boston Jet Physics"
    org: Harvard/MIT
    dates: January 2014
    
  - job:  Advisory Committee
    issue: "Boost 2013"
    org: Flagstaff
    dates: August 2013
    
  - job:  Advisory Committee
    issue: "Boost 2012"
    org: Valencia
    dates: July 2012
    
  - job: Conference Program Committee
    issue: "PANIC 2011: Particle and Nuclei International Conference"
    org: Boston
    dates: July 2011
    
  - job:  Organizer
    issue: "Boston Jet Physics"
    org: Harvard/MIT
    dates: January 2011
    
  - job:  Organizer
    issue: "Implications of First LHC Data"
    org: MIT/Berkeley
    dates: August 2010
    
  - job:  Advisory Committee
    issue: "Boost 2010"
    org: Oxford U.
    dates: June 2010
